(function(){
  'use strict';
  const root=document.querySelector('[data-glossary-games]');
  const library=window.RPSGTV2FlashcardLibrary;
  const storage=window.RPSGTStorage;
  if(!root||!library)return;
  const panel=root.querySelector('[data-glossary-panel]');
  const modeButtons=[...root.querySelectorAll('[data-glossary-mode]')];
  const text=value=>String(value==null?'':value).trim();
  const shuffle=values=>{const copy=values.slice();for(let i=copy.length-1;i>0;i-=1){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;};
  let items=[],mode='match',weak=new Map(),score=0,attempts=0,selected=[];
  function loadWeak(){try{const saved=storage?.load?.()||{};weak=new Map(Object.entries(saved.glossaryGames?.weak||{}).map(([key,value])=>[key,Number(value)||0]));}catch(error){weak=new Map();}}
  function saveWeak(){if(!storage?.load||!storage?.save)return;const saved=storage.load();saved.glossaryGames=saved.glossaryGames||{};saved.glossaryGames.weak=Object.fromEntries(weak);storage.save(saved);}
  function record(id,correct){const current=weak.get(id)||0;weak.set(id,correct?Math.max(0,current-1):current+1);saveWeak();}
  function pool(){if(mode!=='weak')return items;const hard=items.filter(item=>(weak.get(item.id)||0)>0).sort((a,b)=>(weak.get(b.id)||0)-(weak.get(a.id)||0));return hard.length>=4?hard:items;}
  function stats(){return '<div class="glossary-stats"><div class="glossary-stat"><span>Correct</span><strong data-glossary-correct>'+score+'</strong></div><div class="glossary-stat"><span>Attempts</span><strong data-glossary-attempts>'+attempts+'</strong></div><div class="glossary-stat"><span>Weak terms</span><strong>'+[...weak.values()].filter(v=>v>0).length+'</strong></div></div>';}
  function match(){score=0;attempts=0;selected=[];const chosen=shuffle(pool()).slice(0,6);const tiles=shuffle(chosen.flatMap(item=>[{id:item.id,key:item.id+':term',label:item.term,pair:item.id},{id:item.id,key:item.id+':def',label:item.definition,pair:item.id}]));panel.innerHTML=stats()+'<div class="glossary-match-board" data-glossary-board></div><div class="glossary-feedback" data-glossary-feedback>Match each term with its definition.</div><div class="actions"><button class="btn secondary" type="button" data-glossary-new>New board</button></div>';const board=panel.querySelector('[data-glossary-board]');tiles.forEach(tile=>{const b=document.createElement('button');b.type='button';b.className='glossary-tile';b.textContent=tile.label;b.addEventListener('click',()=>pick(b,tile));board.appendChild(b);});panel.querySelector('[data-glossary-new]').addEventListener('click',match);}
  function pick(button,tile){if(button.classList.contains('matched')||button.classList.contains('selected')||selected.length>=2)return;button.classList.add('selected');selected.push({button,tile});if(selected.length<2)return;attempts+=1;const [a,b]=selected;const ok=a.tile.pair===b.tile.pair&&a.tile.key!==b.tile.key;if(ok){score+=1;a.button.classList.remove('selected');b.button.classList.remove('selected');a.button.classList.add('matched');b.button.classList.add('matched');record(a.tile.id,true);selected=[];panel.querySelector('[data-glossary-feedback]').textContent='Match found.';}else{record(a.tile.id,false);record(b.tile.id,false);a.button.classList.add('wrong');b.button.classList.add('wrong');setTimeout(()=>{a.button.classList.remove('selected','wrong');b.button.classList.remove('selected','wrong');selected=[];},600);panel.querySelector('[data-glossary-feedback]').textContent='Not a match. Compare the wording and try again.';}updateStats();}
  function recall(reverse){const list=pool();if(list.length<4){panel.innerHTML='<div class="glossary-feedback incorrect">Not enough glossary items are available.</div>';return;}const target=shuffle(list)[0];const prompt=reverse?target.definition:target.term;const correct=reverse?target.term:target.definition;const distractors=shuffle(list.filter(item=>item.id!==target.id)).slice(0,3).map(item=>reverse?item.term:item.definition);const choices=shuffle([correct,...distractors]);panel.innerHTML=stats()+'<div class="glossary-prompt"><small>'+(reverse?'Definition → Term':'Term → Definition')+'</small><strong>'+prompt+'</strong></div><div class="glossary-choice-grid" data-glossary-choices></div><div class="glossary-feedback" data-glossary-feedback>Choose the best match.</div><div class="actions"><button class="btn primary" type="button" data-glossary-next disabled>Next</button></div>';const host=panel.querySelector('[data-glossary-choices]');choices.forEach(value=>{const b=document.createElement('button');b.type='button';b.className='glossary-choice';b.textContent=value;b.addEventListener('click',()=>{if(host.dataset.locked)return;host.dataset.locked='1';attempts+=1;const ok=value===correct;if(ok)score+=1;[...host.children].forEach(choice=>{choice.disabled=true;if(choice.textContent===correct)choice.classList.add('correct');});if(!ok)b.classList.add('incorrect');record(target.id,ok);const feedback=panel.querySelector('[data-glossary-feedback]');feedback.className='glossary-feedback '+(ok?'':'incorrect');feedback.innerHTML=ok?'<strong>Correct.</strong>':'<strong>Review it.</strong> The correct match is '+correct+'.';panel.querySelector('[data-glossary-next]').disabled=false;updateStats();});host.appendChild(b);});panel.querySelector('[data-glossary-next]').addEventListener('click',()=>recall(reverse));}
  function updateStats(){const c=panel.querySelector('[data-glossary-correct]'),a=panel.querySelector('[data-glossary-attempts]');if(c)c.textContent=score;if(a)a.textContent=attempts;}
  function setMode(value){mode=value;score=0;attempts=0;modeButtons.forEach(button=>button.classList.toggle('active',button.dataset.glossaryMode===value));if(value==='match')match();else if(value==='term-definition')recall(false);else if(value==='definition-term')recall(true);else recall(Math.random()>.5);}
  modeButtons.forEach(button=>button.addEventListener('click',()=>setMode(button.dataset.glossaryMode)));
  async function init(){try{await library.load();items=library.asV3Cards().map(card=>({id:text(card.id),term:text(card.front),definition:text(card.back),category:text(card.category)})).filter(item=>item.term&&item.definition);loadWeak();setMode(mode);}catch(error){panel.innerHTML='<div class="glossary-feedback incorrect"><strong>Glossary Games could not load.</strong> '+error.message+'</div>';}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
