(function(){
  'use strict';
  const engine=window.RPSGTVisualLabEngine;
  const renderer=window.RPSGTVisualPSGRenderer;
  const workspace=document.querySelector('[data-visual-workspace]');
  const summaryHost=document.querySelector('[data-visual-summary]');
  const startButton=document.querySelector('[data-visual-start]');
  if(!workspace||!summaryHost||!startButton)return;
  const state={saved:null,pack:null,session:null,index:0,answers:{},locked:new Set(),finished:null,metrics:null,drag:null};
  const esc=value=>String(value==null?'':value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const formatDate=value=>value?new Date(value).toLocaleString():'—';
  async function loadJson(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(path+' HTTP '+response.status);return response.json();}
  async function loadPack(){const [base,supplement]=await Promise.all([loadJson('data/visual/prototype-sleep-staging.json'),loadJson('data/visual/pack1-intervals.json')]);if(!supplement.meta||supplement.meta.appAuthored!==true)throw new Error('Visual interval supplement is not approved as app-authored content.');base.questions=[...(base.questions||[]),...(supplement.questions||[])];base.meta.supplements=['pack1-intervals.json'];return base;}
  function saveLabs(nextLabs){state.saved.labs=nextLabs;state.saved=window.RPSGTStorage.save(state.saved);}
  function renderSummary(){const report=engine.summary(state.saved.labs);summaryHost.innerHTML=`<div><span>Status</span><strong>${report.startedAt?'Staging Pack started':'Not started'}</strong></div><div><span>Saved attempts</span><strong>${report.attempts}</strong></div><div><span>Best Pack 1 score</span><strong>${report.attempts?report.bestPercent+'%':'—'}</strong></div><div><span>Last attempt</span><strong>${report.latestSession?formatDate(report.latestSession.completedAt):'—'}</strong></div>`;startButton.textContent=report.attempts?'Practice Sleep Staging Pack 1 again':'Start Sleep Staging Pack 1';}
  function currentQuestion(){return state.session&&state.session.questions[state.index]||null;}
  function currentStudy(){const question=currentQuestion();return question?state.session.studies.get(String(question.studyId)):null;}
  function allLocked(){return Boolean(state.session)&&state.locked.size===state.session.questions.length;}
  function stageQuestionForStudy(studyId){return state.session?state.session.questions.find(question=>String(question.studyId)===String(studyId)&&question.type==='stage-choice')||null:null;}
  function stageRevealed(studyId){const question=stageQuestionForStudy(studyId);return Boolean(question)&&state.locked.has(String(question.id));}
  function currentEpochIndex(){const question=currentQuestion();return question&&state.session?state.session.studyOrder.indexOf(String(question.studyId)):-1;}
  function firstQuestionIndexForStudy(studyId){return state.session?state.session.questions.findIndex(question=>String(question.studyId)===String(studyId)):-1;}
  function studyProgress(studyId){const questions=state.session?state.session.questions.filter(question=>String(question.studyId)===String(studyId)):[];return {locked:questions.filter(question=>state.locked.has(String(question.id))).length,total:questions.length};}
  function epochNavMarkup(){if(!state.session)return '';const current=currentQuestion(),currentStudyId=current?String(current.studyId):'';return `<nav class="visual-epoch-nav" aria-label="Teaching epoch navigator">${state.session.studyOrder.map((studyId,index)=>{const study=state.session.studies.get(String(studyId)),revealed=stageRevealed(studyId),progress=studyProgress(studyId),classes=['visual-epoch-button'];if(String(studyId)===currentStudyId)classes.push('current');if(progress.total&&progress.locked===progress.total)classes.push('complete');const stageText=revealed&&study&&study.stage?' · '+study.stage:'';return `<button class="${classes.join(' ')}" type="button" data-visual-epoch="${esc(studyId)}" aria-current="${String(studyId)===currentStudyId?'true':'false'}"><strong>Epoch ${index+1}${esc(stageText)}</strong><small>${progress.locked}/${progress.total} reviewed</small></button>`;}).join('')}</nav>`;}
  function addPointMarker(layer,selection,className,label){const position=renderer.pointPosition(state.metrics,selection);if(!position)return;const marker=document.createElement('span');marker.className=className;marker.style.left=position.left+'px';marker.style.top=position.top+'px';marker.setAttribute('aria-label',label||'Selected point');layer.appendChild(marker);}
  function addIntervalBox(layer,interval,className){if(!interval)return;const box=renderer.regionStyle(state.metrics,{start:interval.start,end:interval.end},interval.channel);if(box.top==null)return;const element=document.createElement('span');element.className=className;element.style.left=box.left+'px';element.style.top=box.top+'px';element.style.width=Math.max(5,box.width)+'px';element.style.height=box.height+'px';element.setAttribute('aria-hidden','true');layer.appendChild(element);return element;}
  function renderOverlay(question){
    const layer=workspace.querySelector('[data-visual-region-layer]');if(!layer||!state.metrics)return;layer.innerHTML='';if(!question)return;
    const selected=state.answers[String(question.id)]||null,locked=state.locked.has(String(question.id));
    if(question.type==='region-choice'){question.regions.forEach(region=>{const box=renderer.regionStyle(state.metrics,region,question.channel),button=document.createElement('button');button.type='button';button.className='visual-region-button';button.dataset.visualRegion=region.id;button.style.left=box.left+'px';button.style.width=box.width+'px';if(box.top!=null){button.style.top=box.top+'px';button.style.height=box.height+'px';button.style.bottom='auto';}button.setAttribute('aria-label','Select '+region.label+' time region');if(selected===region.id)button.classList.add('selected');if(locked){button.classList.add('locked');button.disabled=true;if(region.id===question.answer)button.classList.add('correct');if(selected===region.id&&selected!==question.answer)button.classList.add('incorrect');}layer.appendChild(button);});return;}
    if(question.type==='point-click'){
      const surface=document.createElement('button');surface.type='button';surface.className='visual-point-surface';surface.dataset.visualPointSurface='true';surface.style.left=state.metrics.labelWidth+'px';surface.style.top=state.metrics.topPad+'px';surface.style.width=(state.metrics.plotRight-state.metrics.labelWidth)+'px';surface.style.height=(state.metrics.channels.length*state.metrics.rowHeight)+'px';surface.setAttribute('aria-label','Click a channel and time point on the PSG tracing');if(locked)surface.disabled=true;layer.appendChild(surface);
      if(locked){const target=renderer.targetStyle(state.metrics,question.target),targetBox=document.createElement('span');targetBox.className='visual-point-target';targetBox.style.left=target.left+'px';targetBox.style.top=target.top+'px';targetBox.style.width=Math.max(8,target.width)+'px';targetBox.style.height=target.height+'px';targetBox.setAttribute('aria-hidden','true');layer.appendChild(targetBox);}
      if(selected){const grade=engine.gradeAnswer(question,selected);addPointMarker(layer,selected,'visual-point-marker '+(locked?(grade.correct?'correct':'incorrect'):'selected'),'Selected channel and time');}return;
    }
    if(question.type==='interval-mark'){
      const surface=document.createElement('div');surface.className='visual-interval-surface';surface.dataset.visualIntervalSurface='true';surface.style.left=state.metrics.labelWidth+'px';surface.style.top=state.metrics.topPad+'px';surface.style.width=(state.metrics.plotRight-state.metrics.labelWidth)+'px';surface.style.height=(state.metrics.channels.length*state.metrics.rowHeight)+'px';surface.setAttribute('role','application');surface.setAttribute('aria-label','Drag across one signal channel to mark the requested interval');if(locked)surface.classList.add('locked');layer.appendChild(surface);
      if(locked)addIntervalBox(layer,question.target,'visual-interval-target');
      if(selected){const interval=engine.parseInterval(selected),grade=engine.gradeAnswer(question,selected);addIntervalBox(layer,interval,'visual-interval-selection '+(locked?(grade.correct?'correct':'incorrect'):'selected'));}return;
    }
  }
  function renderCanvas(){const canvas=workspace.querySelector('[data-visual-canvas]'),study=currentStudy(),question=currentQuestion();if(!canvas||!study)return;state.metrics=renderer.render(canvas,study);renderOverlay(question);}
  function choiceButton(value,label,question){const selected=state.answers[String(question.id)]===value,locked=state.locked.has(String(question.id)),grade=locked?engine.gradeAnswer(question,value):null;let classes='visual-choice';if(selected)classes+=' selected';if(locked&&grade&&grade.correct)classes+=' correct';if(locked&&selected&&grade&&!grade.correct)classes+=' incorrect';return `<button class="${classes}" type="button" data-visual-answer="${esc(value)}" ${locked?'disabled':''}>${esc(label)}</button>`;}
  function renderQuestionControls(question){
    if(question.type==='stage-choice')return `<div class="visual-stage-options" role="group" aria-label="Sleep stage choices">${question.options.map(option=>choiceButton(option,option,question)).join('')}</div>`;
    if(question.type==='region-choice')return `<div class="visual-region-options" role="group" aria-label="Time region choices">${question.regions.map(region=>choiceButton(region.id,region.label,question)).join('')}</div>`;
    if(question.type==='point-click')return `<div class="visual-point-help"><strong>Precision mode:</strong> click directly on the requested channel and feature. The buttons below provide a keyboard-friendly alternative.</div><div class="visual-point-options" role="group" aria-label="Alternative channel and time points">${(question.fallbackPoints||[]).map(point=>choiceButton(String(point.channel)+'@'+Number(point.time).toFixed(2),point.label,question)).join('')}</div>`;
    if(question.type==='interval-mark')return `<div class="visual-point-help"><strong>Duration mode:</strong> press or touch at the beginning of the feature, drag along the same channel, and release at the end. The choices below provide a keyboard-friendly alternative.</div><div class="visual-interval-options" role="group" aria-label="Alternative marked intervals">${(question.fallbackIntervals||[]).map(item=>choiceButton(String(item.channel)+'@'+Number(item.start).toFixed(2)+'-'+Number(item.end).toFixed(2),item.label,question)).join('')}</div>`;
    return '';
  }
  function feedbackMarkup(question){if(!state.locked.has(String(question.id)))return '';const grade=engine.gradeAnswer(question,state.answers[String(question.id)]);let answerLabel=question.answer;if(question.type==='region-choice')answerLabel=(question.regions.find(region=>region.id===question.answer)||{}).label||question.answer;if(question.type==='point-click'||question.type==='interval-mark')answerLabel=question.target.channel+' · '+question.target.start+'–'+question.target.end+' s';return `<div class="visual-feedback ${grade.correct?'correct':'retry'}"><strong>${grade.correct?'Correct':'Review this feature'} · Target: ${esc(answerLabel)}</strong><span>${esc(question.rationale||'Review the complete signal context before continuing.')}</span></div>`;}
  function actionMarkup(question){const locked=state.locked.has(String(question.id)),last=state.index===state.session.questions.length-1;return `<div class="visual-question-actions">${state.index>0?'<button class="btn secondary" type="button" data-visual-prev>Previous question</button>':''}${!locked?'<button class="btn primary" type="button" data-visual-check>Check answer</button>':!last?'<button class="btn primary" type="button" data-visual-next>Next question</button>':allLocked()?'<button class="btn primary" type="button" data-visual-finish>Save Pack 1 attempt</button>':''}<button class="btn secondary" type="button" data-visual-close>Close</button></div>`;}
  function renderFinished(){const record=state.finished;workspace.hidden=false;workspace.innerHTML=`<div class="visual-result"><div class="eyebrow">Sleep Staging Pack 1 saved</div><h2>${record.correct}/${record.total} correct · ${record.percent}%</h2><p>This result is Visual Skills practice evidence only. It is not a readiness score, mock-exam score, ISR result, or scoring-competency determination.</p><div class="actions"><button class="btn primary" type="button" data-visual-restart>Practice Pack 1 again</button><a class="btn secondary" href="labs.html">Return to Skills Labs</a></div></div>`;}
  function renderWorkspace(){
    if(state.finished){renderFinished();return;}const question=currentQuestion(),study=currentStudy();if(!question||!study)return;
    const epochIndex=currentEpochIndex(),revealed=stageRevealed(question.studyId),reviewStage=revealed&&study.stage?' · Review stage: '+study.stage:'';
    const interaction=question.type==='point-click'?'Click the requested feature in the correct channel. Your click is resolved to channel and time.':question.type==='interval-mark'?'Drag across the requested feature to mark its beginning and end on one channel.':question.type==='region-choice'?'Select the requested time region.':'Review EEG, EOG, chin tone, and neighboring signals before choosing the stage.';
    workspace.hidden=false;workspace.innerHTML=`<div class="section-head"><div><div class="eyebrow">Mini PSG Viewer · ${esc(question.taskCode||'Visual')}</div><h2>Epoch ${epochIndex+1} of ${state.session.studyOrder.length}${esc(reviewStage)}</h2></div><span class="status">Original schematic signal</span></div>${epochNavMarkup()}<div class="visual-study-meta"><span class="status">Five-stage challenge</span><span class="status">30-second epoch</span><span class="status">${study.channels.length} channels</span><span class="status">Question ${state.index+1} of ${state.session.questions.length}</span></div><div class="visual-viewer-shell"><div class="visual-viewer-head"><div><strong>PSG signal window</strong><small>Canvas-rendered from app-authored signal definitions</small></div><span class="status green">No patient data</span></div><div class="visual-scroll"><div class="visual-canvas-stage" data-visual-stage><canvas data-visual-canvas aria-label="Schematic polysomnography tracing"></canvas><div class="visual-region-layer" data-visual-region-layer aria-label="Interactive PSG annotation layer"></div></div></div></div><section class="visual-question-card"><div class="visual-question-top"><div><h2>${esc(question.prompt)}</h2><p>${esc(interaction)}</p></div><span class="visual-counter">${state.index+1}/${state.session.questions.length}</span></div>${renderQuestionControls(question)}${feedbackMarkup(question)}${actionMarkup(question)}</section>`;requestAnimationFrame(renderCanvas);
  }
  function selectAnswer(value){const question=currentQuestion();if(!question||state.locked.has(String(question.id)))return;state.answers[String(question.id)]=String(value);renderWorkspace();}
  function selectPoint(event,surface){const question=currentQuestion();if(!question||question.type!=='point-click'||state.locked.has(String(question.id))||!state.metrics)return;const rect=surface.getBoundingClientRect(),x=event.clientX-rect.left+state.metrics.labelWidth,y=event.clientY-rect.top+state.metrics.topPad,point=renderer.hitTest(state.metrics,x,y);if(!point)return;state.answers[String(question.id)]=point.channel+'@'+point.time.toFixed(2);renderWorkspace();}
  function intervalPoint(event,surface,channelIndex){const rect=surface.getBoundingClientRect(),x=event.clientX-rect.left+state.metrics.labelWidth,y=channelIndex==null?event.clientY-rect.top+state.metrics.topPad:state.metrics.topPad+channelIndex*state.metrics.rowHeight+state.metrics.rowHeight/2;return renderer.hitTest(state.metrics,x,y);}
  function updateDragPreview(interval){const layer=workspace.querySelector('[data-visual-region-layer]');if(!layer)return;const old=layer.querySelector('[data-visual-drag-preview]');if(old)old.remove();const element=addIntervalBox(layer,interval,'visual-interval-selection dragging');if(element)element.dataset.visualDragPreview='true';}
  function beginIntervalDrag(event,surface){const question=currentQuestion();if(!question||question.type!=='interval-mark'||state.locked.has(String(question.id))||!state.metrics)return;const point=intervalPoint(event,surface,null);if(!point)return;event.preventDefault();if(surface.setPointerCapture)surface.setPointerCapture(event.pointerId);state.drag={questionId:String(question.id),pointerId:event.pointerId,surface,channel:point.channel,channelIndex:point.channelIndex,start:point.time,end:point.time};updateDragPreview({channel:point.channel,start:point.time,end:point.time});}
  function moveIntervalDrag(event){if(!state.drag||event.pointerId!==state.drag.pointerId||!state.metrics)return;const point=intervalPoint(event,state.drag.surface,state.drag.channelIndex);if(!point)return;event.preventDefault();state.drag.end=point.time;updateDragPreview({channel:state.drag.channel,start:Math.min(state.drag.start,state.drag.end),end:Math.max(state.drag.start,state.drag.end)});}
  function endIntervalDrag(event){if(!state.drag||event.pointerId!==state.drag.pointerId)return;const drag=state.drag;moveIntervalDrag(event);state.drag=null;const start=Math.min(drag.start,drag.end),end=Math.max(drag.start,drag.end);if(end-start<.05){renderWorkspace();return;}state.answers[drag.questionId]=drag.channel+'@'+start.toFixed(2)+'-'+end.toFixed(2);renderWorkspace();}
  function checkAnswer(){const question=currentQuestion();if(!question)return;if(state.answers[String(question.id)]==null){const card=workspace.querySelector('.visual-question-card');if(card){const note=document.createElement('div');note.className='visual-feedback retry';note.innerHTML='<strong>Select an answer first.</strong><span>Use the tracing or the accessible choices before checking the item.</span>';card.appendChild(note);}return;}state.locked.add(String(question.id));renderWorkspace();}
  function jumpToEpoch(studyId){const index=firstQuestionIndexForStudy(studyId);if(index<0)return;state.index=index;state.drag=null;renderWorkspace();}
  function finish(){if(!allLocked())return;const record=engine.gradeSession({questions:state.session.questions,answers:state.answers,completedAt:new Date().toISOString()});saveLabs(engine.applySession(state.saved.labs,record));state.finished=record;state.drag=null;renderSummary();renderFinished();}
  function startSession(){saveLabs(engine.start(state.saved.labs,new Date().toISOString()));state.session=engine.buildSession(state.pack,new Date().toISOString());state.index=0;state.answers={};state.locked=new Set();state.finished=null;state.drag=null;renderSummary();renderWorkspace();workspace.scrollIntoView({behavior:'smooth',block:'start'});}
  function closeSession(){state.session=null;state.answers={};state.locked=new Set();state.finished=null;state.metrics=null;state.drag=null;workspace.hidden=true;workspace.innerHTML='';}
  async function init(){try{if(!engine||!renderer||!window.RPSGTStorage)throw new Error('A required Visual Skills module is unavailable.');state.saved=window.RPSGTStorage.load();state.pack=await loadPack();const validation=engine.validatePack(state.pack);if(!validation.valid)throw new Error('Visual staging pack failed validation: '+validation.issues.join(', '));renderSummary();}catch(error){workspace.hidden=false;workspace.innerHTML=`<div class="notice error"><strong>Visual staging pack could not load.</strong> ${esc(error.message)} No learner progress was changed.</div>`;startButton.disabled=true;}}
  startButton.addEventListener('click',startSession);
  document.addEventListener('pointerdown',event=>{const surface=event.target.closest('[data-visual-interval-surface]');if(surface)beginIntervalDrag(event,surface);});
  document.addEventListener('pointermove',moveIntervalDrag,{passive:false});document.addEventListener('pointerup',endIntervalDrag);document.addEventListener('pointercancel',event=>{if(state.drag&&event.pointerId===state.drag.pointerId){state.drag=null;renderWorkspace();}});
  document.addEventListener('click',event=>{const epoch=event.target.closest('[data-visual-epoch]');if(epoch){jumpToEpoch(epoch.dataset.visualEpoch);return;}const pointSurface=event.target.closest('[data-visual-point-surface]');if(pointSurface){selectPoint(event,pointSurface);return;}const answer=event.target.closest('[data-visual-answer]');if(answer){selectAnswer(answer.dataset.visualAnswer);return;}const region=event.target.closest('[data-visual-region]');if(region){selectAnswer(region.dataset.visualRegion);return;}if(event.target.closest('[data-visual-check]')){checkAnswer();return;}if(event.target.closest('[data-visual-prev]')){state.index=Math.max(0,state.index-1);state.drag=null;renderWorkspace();return;}if(event.target.closest('[data-visual-next]')){state.index=Math.min(state.session.questions.length-1,state.index+1);state.drag=null;renderWorkspace();return;}if(event.target.closest('[data-visual-finish]')){finish();return;}if(event.target.closest('[data-visual-restart]')){startSession();return;}if(event.target.closest('[data-visual-close]'))closeSession();});
  let resizeTimer=null;window.addEventListener('resize',()=>{if(!state.session||workspace.hidden)return;clearTimeout(resizeTimer);resizeTimer=setTimeout(renderCanvas,100);});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
