(function(){
  'use strict';
  const engine=window.RPSGTMathCoachEngine;const app=window.RPSGTMathCoachApp;
  const summaryHost=document.querySelector('[data-math-summary]');const catalogHost=document.querySelector('[data-math-catalog]');const workspace=document.querySelector('[data-math-workspace]');const awardOverlay=document.querySelector('[data-math-award-overlay]');const awardHost=document.querySelector('[data-math-award]');
  if(!app||!summaryHost||!catalogHost||!workspace)return;app.configure({engine,summaryHost,catalogHost,workspace,awardOverlay,awardHost});const state=app.state;
  async function loadJson(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(path+' HTTP '+response.status);return response.json();}
  function saveMath(next){state.saved.mathCoach=next;state.saved=window.RPSGTStorage.save(state.saved);}
  function clearQuestionUi(){state.guidedFeedback=null;state.setFeedback=null;state.guidedQuestionId=null;state.questionReviewKind=null;app.resetQuestionHelp();}
  function openSkill(skillId){if(!app.skillById(skillId))return;state.returnFocus=document.activeElement;state.currentSkill=skillId;clearQuestionUi();saveMath(engine.startSkill(state.saved.mathCoach,state.catalog,skillId,new Date().toISOString()));app.refresh();}
  function changeStage(stage){if(!state.currentSkill)return;clearQuestionUi();saveMath(engine.setStage(state.saved.mathCoach,state.catalog,state.currentSkill,stage,new Date().toISOString()));app.refresh();}
  function closeWorkspace(){state.currentSkill=null;clearQuestionUi();workspace.hidden=true;workspace.innerHTML='';document.body.classList.remove('math-question-modal-open');app.renderCatalog();if(state.returnFocus&&typeof state.returnFocus.focus==='function')state.returnFocus.focus({preventScroll:true});state.returnFocus=null;}
  function collectAnswers(form,questions){const answers={};questions.forEach(question=>{const input=form.elements.namedItem(question.id);answers[question.id]=input&&input.value;});return answers;}
  function pinWhiteboard(question,response,kind){state.whiteboardOpen=true;state.whiteboardPinned=true;state.whiteboardQuestionId=question&&question.id||response&&response.id||null;state.whiteboardResponse=response||null;state.whiteboardKind=kind||null;}
  function submitGuided(form){
    const skill=app.skillById(state.currentSkill);const record=app.recordFor(skill.id);const question=app.guidedQuestion(skill,record);const result=engine.numericResult(question,form.elements.answer.value);state.guidedFeedback={...result,questionId:question.id};
    if(result.answered){saveMath(engine.recordGuided(state.saved.mathCoach,state.catalog,skill.id,state.guidedFeedback,new Date().toISOString()));if(!result.correct)pinWhiteboard(question,state.guidedFeedback,'guided');else{state.guidedQuestionId=null;app.resetQuestionHelp();}}
    app.renderSummary();app.renderCatalog();app.renderWorkspace();
  }
  function submitSet(form,kind){
    const skill=app.skillById(state.currentSkill);const questions=kind==='mastery'?skill.mastery:skill.independent;const grade=engine.gradeSet(questions,collectAnswers(form,questions));const firstMissed=grade.responses.find(response=>!response.correct)||null;
    if(kind==='mastery'){
      const outcome=engine.recordMastery(state.saved.mathCoach,state.catalog,skill.id,grade,new Date().toISOString(),state.catalog.passPercent);saveMath(outcome.state);state.setFeedback={...grade,passed:outcome.passed,heading:outcome.passed?'Mastery demonstrated':'Review and retry',message:outcome.passed?'You reached the mastery standard.':'Use the answer review to find the formula or unit step that needs another pass.'};state.questionReviewKind=outcome.passed?null:'mastery';if(firstMissed&&!outcome.passed)pinWhiteboard(app.questionById(skill,firstMissed.id),firstMissed,'mastery');else if(outcome.passed)app.resetQuestionHelp();app.renderSummary();app.renderCatalog();app.renderWorkspace();if(outcome.earnedNow&&outcome.award)showAward(outcome.award);
    }else{
      const threshold=Number(state.catalog.independentAdvancePercent||engine.INDEPENDENT_ADVANCE_PERCENT);saveMath(engine.recordIndependent(state.saved.mathCoach,state.catalog,skill.id,grade,new Date().toISOString(),threshold));state.setFeedback={...grade,passed:grade.percent>=threshold,heading:grade.percent>=threshold?'Ready for the mastery check':'Practice this pathway again',message:grade.percent>=threshold?'Review your result, then continue when you are ready.':'Review the missed setups, keep the whiteboard pinned, then repeat independent practice.'};state.questionReviewKind='independent';if(firstMissed)pinWhiteboard(app.questionById(skill,firstMissed.id),firstMissed,'independent');else app.resetQuestionHelp();app.renderSummary();app.renderCatalog();app.renderWorkspace();
    }
  }
  function showAward(award){if(!awardOverlay||!awardHost)return;const seen=new Set(state.saved.awards&&state.saved.awards.seenCeremonyIds||[]);if(seen.has(award.id))return;awardHost.innerHTML=`<button class="icon-close" type="button" data-math-award-close aria-label="Close award ceremony">×</button><div class="math-award-medal" aria-hidden="true">🏅</div><span class="status green">New mastery medal</span><h2 id="math-award-title">${app.esc(award.title)}</h2><p>${app.esc(award.skillTitle)}</p><blockquote>“${app.esc(award.message)}”</blockquote><div class="actions"><button class="btn primary" type="button" data-math-award-close>Continue</button><a class="btn secondary" href="reports.html">View progress</a></div>`;awardOverlay.hidden=false;document.body.classList.add('math-award-open');requestAnimationFrame(()=>awardHost.focus({preventScroll:true}));}
  function closeAward(){if(!awardOverlay||awardOverlay.hidden)return;const skill=state.currentSkill&&app.skillById(state.currentSkill);if(skill){const id='math-skill-'+skill.id;state.saved.awards=state.saved.awards||{seenCeremonyIds:[]};state.saved.awards.seenCeremonyIds=[...new Set([...(state.saved.awards.seenCeremonyIds||[]),id])];state.saved=window.RPSGTStorage.save(state.saved);}awardOverlay.hidden=true;document.body.classList.remove('math-award-open');}
  function setWhiteboardVisibility(open){
    state.whiteboardOpen=Boolean(open);const board=workspace.querySelector('[data-math-whiteboard]');if(board)board.hidden=!state.whiteboardOpen;const hint=workspace.querySelector('[data-math-hint]');if(hint){hint.setAttribute('aria-expanded',state.whiteboardOpen?'true':'false');hint.textContent=state.whiteboardOpen?'Hide whiteboard help':'Open whiteboard help';}
  }
  async function init(){
    try{
      if(!engine||!window.RPSGTStorage)throw new Error('A required Math Coach module is unavailable.');const manifest=await loadJson('data/math-coach/manifest.json');const skills=await Promise.all((manifest.skillFiles||[]).map(file=>loadJson('data/math-coach/'+file)));state.catalog={...manifest,skills};const validation=engine.validateCatalog(state.catalog);if(!validation.valid)throw new Error('The curated Math Coach catalog did not pass validation.');state.saved=window.RPSGTStorage.load();state.currentSkill=engine.normalizeState(state.saved.mathCoach,state.catalog).currentSkill;app.refresh();
    }catch(error){catalogHost.innerHTML=`<div class="notice error"><strong>Math Coach could not load.</strong> ${app.esc(error.message)} No learner progress was changed.</div>`;workspace.hidden=true;}
  }
  document.addEventListener('click',event=>{
    const open=event.target.closest('[data-math-open]');if(open){openSkill(open.dataset.mathOpen);return;}
    const stage=event.target.closest('[data-math-stage]');if(stage){changeStage(stage.dataset.mathStage);return;}
    if(event.target.closest('[data-math-exit]')){closeWorkspace();return;}
    const hint=event.target.closest('[data-math-hint]');if(hint){const skill=app.skillById(state.currentSkill);const record=skill&&app.recordFor(skill.id);const question=skill&&record?app.guidedQuestion(skill,record):null;if(question){state.whiteboardQuestionId=question.id;state.whiteboardKind='guided';state.whiteboardResponse=state.guidedFeedback;setWhiteboardVisibility(!state.whiteboardOpen);}return;}
    if(event.target.closest('[data-math-whiteboard-pin]')){state.whiteboardPinned=!state.whiteboardPinned;state.whiteboardOpen=true;const board=workspace.querySelector('[data-math-whiteboard]');if(board){board.classList.toggle('pinned',state.whiteboardPinned);board.hidden=false;}const pin=workspace.querySelector('[data-math-whiteboard-pin]');if(pin){pin.setAttribute('aria-pressed',state.whiteboardPinned?'true':'false');pin.textContent=state.whiteboardPinned?'📌 Pinned':'Pin board';}return;}
    if(event.target.closest('[data-math-whiteboard-close]')){state.whiteboardPinned=false;setWhiteboardVisibility(false);return;}
    const explanation=event.target.closest('[data-math-whiteboard-question]');if(explanation){const skill=app.skillById(state.currentSkill);const question=skill&&app.questionById(skill,explanation.dataset.mathWhiteboardQuestion);const response=state.setFeedback&&(state.setFeedback.responses||[]).find(item=>String(item.id)===String(explanation.dataset.mathWhiteboardQuestion));if(question&&response){pinWhiteboard(question,response,explanation.dataset.mathWhiteboardKind);app.renderWorkspace();}return;}
    if(event.target.closest('[data-math-continue-mastery]')){state.questionReviewKind=null;state.setFeedback=null;app.resetQuestionHelp();app.refresh();return;}
    if(event.target.closest('[data-math-practice-again]')&&state.currentSkill){saveMath(engine.resetForPractice(state.saved.mathCoach,state.catalog,state.currentSkill,new Date().toISOString()));clearQuestionUi();app.refresh();return;}
    if(event.target.closest('[data-math-review-skill]')&&state.currentSkill){saveMath(engine.reviewSkill(state.saved.mathCoach,state.catalog,state.currentSkill,new Date().toISOString()));clearQuestionUi();app.refresh();return;}
    const next=event.target.closest('[data-math-next-skill]');if(next){openSkill(next.dataset.mathNextSkill);return;}
    if(event.target.closest('[data-math-award-close]')){closeAward();return;}if(event.target===awardOverlay)closeAward();
  });
  document.addEventListener('submit',event=>{if(event.target.matches('[data-math-guided-form]')){event.preventDefault();submitGuided(event.target);return;}if(event.target.matches('[data-math-set-form]')){event.preventDefault();submitSet(event.target,event.target.dataset.mathSetForm);}});
  document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(event.target&&event.target.closest&&event.target.closest('[data-study-calculator],[data-practice-calculator]'))return;if(awardOverlay&&!awardOverlay.hidden)closeAward();else if(state.currentSkill)closeWorkspace();}});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
