(function(){
  'use strict';
  const root=document.querySelector('[data-memory-arcade]');
  if(!root)return;
  const panel=root.querySelector('[data-arcade-panel]');
  const modeButtons=[...root.querySelectorAll('[data-arcade-mode]')];
  const text=value=>String(value==null?'':value).trim();
  const shuffle=values=>{const copy=values.slice();for(let i=copy.length-1;i>0;i-=1){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;};
  let lessons=[],abbreviations=[],mode='formula-builder',score=0,attempts=0,sprintTimer=null,sprintEnds=0;
  async function json(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(path+' HTTP '+response.status);return response.json();}
  async function load(){const manifest=await json('data/math-coach/manifest.json');lessons=await Promise.all((manifest.skillFiles||[]).map(file=>json('data/math-coach/'+file)));const abbr=await json('data/memory/brpt-rpsgt-abbreviations.json');abbreviations=Array.isArray(abbr.items)?abbr.items:[];}
  function stats(){return '<div class="arcade-stats"><div class="arcade-stat"><span>Correct</span><strong>'+score+'</strong></div><div class="arcade-stat"><span>Attempts</span><strong>'+attempts+'</strong></div><div class="arcade-stat"><span>Mode</span><strong>'+modeButtons.find(b=>b.dataset.arcadeMode===mode)?.querySelector('strong')?.textContent+'</strong></div></div>';}
  function chooseLesson(){return shuffle(lessons)[0];}
  function formulaPieces(formula){const normalized=text(formula).replace(/\s+/g,' ');const split=normalized.split(/(=|÷|×|\+|−|-)/).map(text).filter(Boolean);return split.length>=3?split:normalized.split(' ').filter(Boolean);}
  function builder(){const lesson=chooseLesson();const pieces=formulaPieces(lesson.formula);const bank=shuffle(pieces.map((label,index)=>({label,index})));let answer=[];panel.innerHTML=stats()+'<div class="arcade-prompt"><small>Formula Builder</small><strong>'+lesson.title+'</strong><span>Tap the pieces in the correct order.</span></div><div class="arcade-builder"><div class="arcade-builder-answer" data-builder-answer></div><div class="arcade-builder-bank" data-builder-bank></div></div><div class="arcade-feedback" data-arcade-feedback>Build the formula, then check it.</div><div class="actions"><button class="btn primary" type="button" data-builder-check>Check formula</button><button class="btn secondary" type="button" data-arcade-next>New formula</button></div>';
    const bankHost=panel.querySelector('[data-builder-bank]'),answerHost=panel.querySelector('[data-builder-answer]');
    function render(){bankHost.replaceChildren(...bank.map(piece=>{const b=document.createElement('button');b.type='button';b.className='arcade-piece';b.textContent=piece.label;b.disabled=answer.includes(piece.index);b.classList.toggle('used',b.disabled);b.addEventListener('click',()=>{answer.push(piece.index);render();});return b;}));answerHost.replaceChildren(...answer.map(index=>{const p=pieces[index];const b=document.createElement('button');b.type='button';b.className='arcade-piece';b.textContent=p;b.addEventListener('click',()=>{answer=answer.filter(value=>value!==index);render();});return b;}));}
    render();panel.querySelector('[data-builder-check]').addEventListener('click',()=>{attempts+=1;const result=answer.map(index=>pieces[index]).join('|')===pieces.join('|');if(result)score+=1;const feedback=panel.querySelector('[data-arcade-feedback]');feedback.className='arcade-feedback '+(result?'correct':'incorrect');feedback.innerHTML=result?'<strong>Correct.</strong> '+lesson.formula:'<strong>Try the order again.</strong> Correct formula: '+lesson.formula;renderHeaderStats();});panel.querySelector('[data-arcade-next]').addEventListener('click',builder);}
  function missingPiece(){const lesson=chooseLesson();const pieces=formulaPieces(lesson.formula);const targetIndex=Math.floor(Math.random()*pieces.length);const target=pieces[targetIndex];const visible=pieces.map((piece,index)=>index===targetIndex?'_____':piece).join(' ');const distractors=shuffle(lessons.filter(item=>item.id!==lesson.id).flatMap(item=>formulaPieces(item.formula))).filter(value=>value!==target).slice(0,3);const choices=shuffle([target,...distractors]);panel.innerHTML=stats()+'<div class="arcade-prompt"><small>Missing Formula Piece</small><strong>'+lesson.title+'</strong><span>'+visible+'</span></div><div class="arcade-choice-grid" data-arcade-choices></div><div class="arcade-feedback" data-arcade-feedback>Choose the missing piece.</div><div class="actions"><button class="btn primary" type="button" data-arcade-next disabled>Next</button></div>';wireChoices(choices,target,lesson.formula,missingPiece);}
  function units(){const lesson=chooseLesson();const correct=text(lesson.unit);const pool=[...new Set(lessons.map(item=>text(item.unit)).filter(Boolean))];const fillers=['minutes','percent','events/hour','hours','seconds','µV/mm'].filter(value=>value!==correct);const choices=shuffle([correct,...shuffle([...pool,...fillers].filter(value=>value!==correct)).slice(0,3)]);panel.innerHTML=stats()+'<div class="arcade-prompt"><small>Units Challenge</small><strong>'+lesson.shortTitle+' / '+lesson.title+'</strong><span>Which unit belongs with this calculation?</span></div><div class="arcade-choice-grid" data-arcade-choices></div><div class="arcade-feedback" data-arcade-feedback>Choose the best unit.</div><div class="actions"><button class="btn primary" type="button" data-arcade-next disabled>Next</button></div>';wireChoices(choices,correct,lesson.formula,units);}
  function wireChoices(choices,correct,detail,nextFn){const host=panel.querySelector('[data-arcade-choices]');choices.forEach(value=>{const b=document.createElement('button');b.type='button';b.className='arcade-choice';b.textContent=value;b.addEventListener('click',()=>{if(host.dataset.locked)return;host.dataset.locked='1';attempts+=1;const ok=value===correct;if(ok)score+=1;[...host.children].forEach(choice=>{choice.disabled=true;if(choice.textContent===correct)choice.classList.add('correct');});if(!ok)b.classList.add('incorrect');const feedback=panel.querySelector('[data-arcade-feedback]');feedback.className='arcade-feedback '+(ok?'correct':'incorrect');feedback.innerHTML=(ok?'<strong>Correct.</strong> ':'<strong>Review it.</strong> ')+detail;panel.querySelector('[data-arcade-next]').disabled=false;renderHeaderStats();});host.appendChild(b);});panel.querySelector('[data-arcade-next]').addEventListener('click',nextFn);}
  function sprint(){clearInterval(sprintTimer);score=0;attempts=0;sprintEnds=Date.now()+60000;panel.innerHTML=stats()+'<div class="arcade-sprint"><div class="arcade-sprint-head"><strong>60-second Abbreviation Sprint</strong><span class="status gold" data-sprint-time>60 s</span></div><div class="arcade-prompt"><small>What does this mean?</small><strong data-sprint-prompt></strong></div><div class="arcade-choice-grid" data-arcade-choices></div><div class="arcade-feedback" data-arcade-feedback>Answer as many as you can before time runs out.</div></div>';nextSprint();sprintTimer=setInterval(()=>{const left=Math.max(0,Math.ceil((sprintEnds-Date.now())/1000));const node=panel.querySelector('[data-sprint-time]');if(node)node.textContent=left+' s';if(left<=0){clearInterval(sprintTimer);panel.querySelectorAll('.arcade-choice').forEach(button=>button.disabled=true);const feedback=panel.querySelector('[data-arcade-feedback]');if(feedback)feedback.innerHTML='<strong>Time.</strong> '+score+' correct out of '+attempts+' attempts.';}},250);}
  function nextSprint(){if(Date.now()>=sprintEnds)return;const target=shuffle(abbreviations)[0];const distractors=shuffle(abbreviations.filter(item=>item.abbreviation!==target.abbreviation)).slice(0,3).map(item=>item.meaning);const choices=shuffle([target.meaning,...distractors]);const prompt=panel.querySelector('[data-sprint-prompt]'),host=panel.querySelector('[data-arcade-choices]');if(!prompt||!host)return;prompt.textContent=target.abbreviation;host.replaceChildren(...choices.map(value=>{const b=document.createElement('button');b.type='button';b.className='arcade-choice';b.textContent=value;b.addEventListener('click',()=>{attempts+=1;const ok=value===target.meaning;if(ok)score+=1;renderHeaderStats();nextSprint();});return b;}));}
  function renderHeaderStats(){const nodes=panel.querySelectorAll('.arcade-stat strong');if(nodes[0])nodes[0].textContent=score;if(nodes[1])nodes[1].textContent=attempts;}
  function setMode(value){clearInterval(sprintTimer);mode=value;score=0;attempts=0;modeButtons.forEach(button=>button.classList.toggle('active',button.dataset.arcadeMode===value));if(value==='formula-builder')builder();else if(value==='missing-piece')missingPiece();else if(value==='units')units();else sprint();}
  modeButtons.forEach(button=>button.addEventListener('click',()=>setMode(button.dataset.arcadeMode)));
  async function init(){try{await load();setMode(mode);}catch(error){panel.innerHTML='<div class="arcade-feedback incorrect"><strong>Memory Arcade could not load.</strong> '+error.message+'</div>';}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
