(function(){
  'use strict';
  const libraryApi=window.RPSGTV2FlashcardLibrary;
  const storage=window.RPSGTStorage;
  const root=document.querySelector('[data-memory-app]');
  if(!root||!libraryApi||!storage)return;
  const text=value=>String(value==null?'':value).trim();
  const shuffle=values=>{const copy=values.slice();for(let i=copy.length-1;i>0;i-=1){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;};
  let cards=[],filtered=[],mode='match',category='all',weak=new Map(),round=null;
  const modeButtons=[...root.querySelectorAll('[data-memory-mode]')];
  const categorySelect=root.querySelector('[data-memory-category]');
  const panel=root.querySelector('[data-memory-panel]');
  const errorNode=root.querySelector('[data-memory-error]');
  function saved(){try{return storage.load();}catch(error){return {};}}
  function persistWeak(){const state=saved();state.memoryGames=state.memoryGames||{};state.memoryGames.weak=Object.fromEntries(weak);storage.save(state);}
  function loadWeak(){const state=saved();const source=state.memoryGames&&state.memoryGames.weak||{};weak=new Map(Object.entries(source).map(([key,value])=>[key,Number(value)||0]));}
  function record(id,correct){if(!id)return;const current=weak.get(id)||0;weak.set(id,correct?Math.max(0,current-1):current+1);persistWeak();}
  function cardPool(){let list=cards;if(category!=='all')list=list.filter(card=>card.category===category);if(mode==='weak')list=list.filter(card=>(weak.get(card.id)||0)>0).sort((a,b)=>(weak.get(b.id)||0)-(weak.get(a.id)||0));return list.length?list:cards;}
  function modeLabel(value){return value==='front-answer'?'Front → Answer':value==='answer-term'?'Answer → Term':value==='weak'?'Weak Memory':'Memory Match';}
  function setMode(value){mode=value;modeButtons.forEach(button=>button.classList.toggle('active',button.dataset.memoryMode===value));start();}
  function renderStats(){const state=saved();const stats=state.memoryGames&&state.memoryGames.stats||{};root.querySelectorAll('[data-memory-stat-rounds]').forEach(n=>n.textContent=Number(stats.rounds||0));root.querySelectorAll('[data-memory-stat-correct]').forEach(n=>n.textContent=Number(stats.correct||0));root.querySelectorAll('[data-memory-stat-weak]').forEach(n=>n.textContent=[...weak.values()].filter(v=>v>0).length);}
  function bump(correct){const state=saved();state.memoryGames=state.memoryGames||{};state.memoryGames.stats=state.memoryGames.stats||{};state.memoryGames.stats.rounds=Number(state.memoryGames.stats.rounds||0)+1;state.memoryGames.stats.correct=Number(state.memoryGames.stats.correct||0)+(correct?1:0);storage.save(state);renderStats();}
  function renderWelcome(){panel.innerHTML='<div class="memory-feedback"><strong>'+modeLabel(mode)+'</strong><br>Select Start Round to begin.</div>';}
  function startMatch(){const chosen=shuffle(cardPool()).slice(0,8);if(chosen.length<2){panel.innerHTML='<div class="memory-feedback">Not enough cards are available for this pool.</div>';return;}const tiles=shuffle(chosen.flatMap(card=>[{id:card.id,key:card.id+':front',label:card.front,pair:card.id},{id:card.id,key:card.id+':back',label:card.back,pair:card.id}]));round={type:'match',selected:[],matched:new Set(),moves:0,total:chosen.length};panel.innerHTML='<div class="memory-stats"><div class="memory-stat"><span>Moves</span><strong data-mm-moves>0</strong></div><div class="memory-stat"><span>Matched</span><strong data-mm-matched>0 / '+chosen.length+'</strong></div><div class="memory-stat"><span>Pairs left</span><strong data-mm-left>'+chosen.length+'</strong></div><div class="memory-stat"><span>Mode</span><strong>Match</strong></div></div><div class="memory-board" data-mm-board></div><div class="memory-feedback" data-mm-feedback>Choose two tiles that belong together.</div>';
    const board=panel.querySelector('[data-mm-board]');tiles.forEach(tile=>{const button=document.createElement('button');button.type='button';button.className='memory-tile';button.dataset.key=tile.key;button.innerHTML='<span class="memory-tile-inner"><span class="memory-tile-face">?</span><span class="memory-tile-face memory-tile-back"></span></span>';button.querySelector('.memory-tile-back').textContent=tile.label;button.addEventListener('click',()=>pickMatch(button,tile));board.appendChild(button);});}
  function pickMatch(button,tile){if(button.classList.contains('matched')||button.classList.contains('flipped')||round.selected.length>=2)return;button.classList.add('flipped');round.selected.push({button,tile});if(round.selected.length<2)return;round.moves+=1;panel.querySelector('[data-mm-moves]').textContent=round.moves;const [a,b]=round.selected;const correct=a.tile.pair===b.tile.pair&&a.tile.key!==b.tile.key;if(correct){a.button.classList.add('matched');b.button.classList.add('matched');round.matched.add(a.tile.pair);record(a.tile.id,true);panel.querySelector('[data-mm-feedback]').textContent='Match found.';finishMatch();round.selected=[];}else{record(a.tile.id,false);record(b.tile.id,false);panel.querySelector('[data-mm-feedback]').textContent='Not a match. Try again.';setTimeout(()=>{a.button.classList.remove('flipped');b.button.classList.remove('flipped');round.selected=[];},600);}}
  function finishMatch(){panel.querySelector('[data-mm-matched]').textContent=round.matched.size+' / '+round.total;panel.querySelector('[data-mm-left]').textContent=round.total-round.matched.size;if(round.matched.size===round.total){bump(true);panel.querySelector('[data-mm-feedback]').innerHTML='<strong>Round complete.</strong> Start another round to reinforce the pairs.';}}
  function startRecall(){const pool=cardPool();if(pool.length<4){panel.innerHTML='<div class="memory-feedback">Not enough cards are available for this recall mode.</div>';return;}const target=shuffle(pool)[0];const reverse=mode==='answer-term';const prompt=reverse?target.back:target.front;const correct=reverse?target.front:target.back;const distractors=shuffle(pool.filter(card=>card.id!==target.id)).slice(0,3).map(card=>reverse?card.front:card.back);const choices=shuffle([correct,...distractors]);round={type:'recall',target,correct,locked:false};panel.innerHTML='<div class="recall-card"><div class="recall-term"></div><div class="recall-choice-grid" data-memory-choices></div><div class="memory-feedback" data-memory-feedback>Choose the best match.</div><div class="actions"><button class="btn primary" type="button" data-memory-next disabled>Next</button></div></div>';panel.querySelector('.recall-term').textContent=prompt;const host=panel.querySelector('[data-memory-choices]');choices.forEach(value=>{const button=document.createElement('button');button.type='button';button.className='recall-choice';button.textContent=value;button.addEventListener('click',()=>answerRecall(button,value));host.appendChild(button);});panel.querySelector('[data-memory-next]').addEventListener('click',startRecall);}
  function answerRecall(button,value){if(round.locked)return;round.locked=true;const correct=value===round.correct;[...panel.querySelectorAll('.recall-choice')].forEach(choice=>{choice.disabled=true;if(choice.textContent===round.correct)choice.classList.add('correct');});if(!correct)button.classList.add('incorrect');record(round.target.id,correct);bump(correct);panel.querySelector('[data-memory-feedback]').innerHTML=correct?'<strong>Correct.</strong> Retrieve it again later to strengthen recall.':'<strong>Review this pair.</strong> The correct match is '+round.correct+'.';panel.querySelector('[data-memory-next]').disabled=false;}
  function start(){if(mode==='match')startMatch();else startRecall();}
  modeButtons.forEach(button=>button.addEventListener('click',()=>setMode(button.dataset.memoryMode)));
  root.querySelectorAll('[data-memory-start]').forEach(button=>button.addEventListener('click',start));
  categorySelect&&categorySelect.addEventListener('change',()=>{category=categorySelect.value||'all';start();});
  async function init(){try{await libraryApi.load();cards=libraryApi.asV3Cards().map(card=>({id:text(card.id),front:text(card.front),back:text(card.back),category:text(card.category)||'RPSGT Review'}));loadWeak();const categories=['all',...new Set(cards.map(card=>card.category).filter(Boolean))];if(categorySelect)categorySelect.replaceChildren(...categories.map(value=>{const option=document.createElement('option');option.value=value;option.textContent=value==='all'?'All categories':value;return option;}));renderStats();renderWelcome();}catch(error){if(errorNode){errorNode.hidden=false;errorNode.textContent='Memory Games could not load: '+error.message;}}}
  window.RPSGTMemoryGames={recordMemoryResult:record,arcadeStats:()=>Object.fromEntries(weak),saveAbbreviationSprint:()=>{},play:()=>{}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
